# Generated by Django 4.2.7 on 2026-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Ожидает оплаты'), ('paid', '💰 Оплачен'), ('processing', '⚙️ В обработке'), ('confirmed', '✅ Подтвержден'), ('shipped', '🚚 Отправлен'), ('completed', '🎉 Завершен'), ('cancelled', '❌ Отменен'), ('refunded', '↩️ Возвращен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
